import { CommonModule } from '@angular/common';
import { Component } from '@angular/core';
import { Employee } from '../../../models/employee';

@Component({
  selector: 'app-employee-table',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './employee-table.component.html',
  styleUrl: './employee-table.component.scss'
})
export class EmployeeTableComponent {
  employees : Employee[] = [
    {
      name: "Alice Smith",
      email: "alice@Tezo.com",
      location: "L5",
      department: "D3",
      role: "R2",
      id: "E2",
      empNo: "TZ002343",
      status: "Active",
      joinDate: "11/15/2022",
      img: "https://randomuser.me/api/portraits/women/50.jpg",
    },
    {
      name: "Michael Brown",
      email: "michael@Tezo.com",
      location: "L1",
      department: "D1",
      role: "R3",
      id: "E3",
      empNo: "TZ002344",
      status: "Active",
      joinDate: "03/05/2023",
      img: "https://randomuser.me/api/portraits/women/51.jpg",
    },
    {
      name: "Sophia Williams",
      email: "sophia@Tezo.com",
      location: "L1",
      department: "D1",
      role: "R4",
      id: "E4",
      empNo: "TZ002345",
      status: "Inactive",
      joinDate: "08/20/2023",
      img: "https://randomuser.me/api/portraits/women/19.jpg",
    },
    {
      name: "James Johnson",
      email: "james@Tezo.com",
      location: "L4",
      department: "D1",
      role: "R5",
      id: "E5",
      empNo: "TZ002346",
      status: "Active",
      joinDate: "09/15/2023",
      img: "https://randomuser.me/api/portraits/women/59.jpg",
    },
    {
      name: "Olivia Garcia",
      email: "olivia@Tezo.com",
      location: "L6",
      department: "D4",
      role: "R6",
      id: "E6",
      empNo: "TZ002347",
      status: "Active",
      joinDate: "06/10/2022",
      img: "https://randomuser.me/api/portraits/women/58.jpg",
    },
    {
      name: "William Martinez",
      email: "william@Tezo.com",
      location: "L1",
      department: "D6",
      role: "R7",
      id: "E7",
      empNo: "TZ002348",
      status: "Inactive",
      joinDate: "01/22/2023",
      img: "https://randomuser.me/api/portraits/women/56.jpg",
    },
    {
      name: "Isabella Hernandez",
      email: "isabella@Tezo.com",
      location: "L1",
      department: "D6",
      role: "R8",
      id: "E8",
      empNo: "TZ002349",
      status: "Active",
      joinDate: "03/30/2023",
      img: "https://randomuser.me/api/portraits/women/91.jpg",
    },
    {
      name: "Ethan Clark",
      email: "ethan@Tezo.com",
      location: "L2",
      department: "D1",
      role: "R4",
      id: "E9",
      empNo: "TZ002350",
      status: "Inactive",
      joinDate: "09/08/2023",
      img: "https://randomuser.me/api/portraits/women/23.jpg",
    },
    {
      name: "Emma Wright",
      email: "emma@Tezo.com",
      location: "L3",
      department: "D1",
      role: "R3",
      id: "E10",
      empNo: "TZ002351",
      status: "Active",
      joinDate: "07/18/2023",
      img: "https://randomuser.me/api/portraits/women/12.jpg",
    },
    {
      name: "Liam Lopez",
      email: "liam@Tezo.com",
      location: "L1",
      department: "D4",
      role: "R9",
      id: "E11",
      empNo: "TZ002352",
      status: "Active",
      joinDate: "02/12/2023",
      img: "https://randomuser.me/api/portraits/women/2.jpg",
    },
    {
      name: "Sophia Scott",
      email: "sophia@Tezo.com",
      location: "L1",
      department: "D1",
      role: "R10",
      id: "E12",
      empNo: "TZ002353",
      status: "Inactive",
      joinDate: "04/05/2023",
      img: "https://randomuser.me/api/portraits/women/20.jpg",
    },
    {
      name: "Benjamin Hall",
      email: "benjamin@Tezo.com",
      location: "L1",
      department: "D6",
      role: "R7",
      id: "E13",
      empNo: "TZ002354",
      status: "Active",
      joinDate: "06/22/2023",
      img: "https://randomuser.me/api/portraits/women/29.jpg",
    },
    {
      name: "Chloe Turner",
      email: "chloe@Tezo.com",
      location: "L1",
      department: "D1",
      role: "R1",
      id: "E14",
      empNo: "TZ002355",
      status: "Active",
      joinDate: "05/12/2022",
      img: "https://randomuser.me/api/portraits/women/62.jpg",
    },
  ];
}
